### ISSUE TITLE
您好,请问如何将调试后的程序打包成ipa包

### ISSUE THREAD

**Issue by yilongmd** [paradiseduo/IPAPatch#1]
您好,非常好用,方便我调试和学习.
想问您一个问题.请问如何蒋已经调试好的程序打包成ipa包

**Comment by AmandaIsLHY** [comment]
文件下载下来后 libhookzz.dylib 就没有，还报错 dyld: Library not loaded: @executable_path/Dylibs/IPAPatchFramework 请问怎么解决

**Comment by paradiseduo** [comment]
> 您好,非常好用,方便我调试和学习.
> 想问您一个问题.请问如何蒋已经调试好的程序打包成ipa包

![image](https://user-images.githubusercontent.com/14846965/69908600-17df9f00-1428-11ea-8a97-f5b45c4a4a7f.png)
右键这个.app文件，选择Show in finder，然后新建一个Payload文件夹，把这个.app文件拖入，右键压缩Payload文件夹，将zip后缀改为ipa后缀即可。

**Comment by paradiseduo** [comment]
> 文件下载下来后 libhookzz.dylib 就没有，还报错 dyld: Library not loaded: @executable_path/Dylibs/IPAPatchFramework 请问怎么解决

![image](https://user-images.githubusercontent.com/14846965/69908634-b53ad300-1428-11ea-9ef2-5e28a1015db4.png)

你是直接git clone的吗？我这边都是正常的，你看一下文件在不在文件夹里
![image](https://user-images.githubusercontent.com/14846965/69908644-da2f4600-1428-11ea-84ec-a3482e683573.png)

**Comment by AmandaIsLHY** [comment]
之前的问题解决了，应该是XCODE版本的原因。
现在我想问一下，我把原来的IPA改了个plist文件再压回去，再用工程运行报 don'thave permission ，工程支持这样操作吗，还是只支持原IPA

**Comment by paradiseduo** [comment]
> 之前的问题解决了，应该是XCODE版本的原因。
> 现在我想问一下，我把原来的IPA改了个plist文件再压回去，再用工程运行报 don'thave permission ，工程支持这样操作吗，还是只支持原IPA

支持修改plist文件的，建议你clean一下再运行试试

**Comment by AmandaIsLHY** [comment]
我试了几种方式，就是原包可以，修改包的plist文件再压回去，再运行就报don'thave permission ，明天我再试试clean,谢谢，如有问题可能还需要请教您

**Comment by paradiseduo** [comment]
> 我试了几种方式，就是原包可以，修改包的plist文件再压回去，再运行就报don'thave permission ，明天我再试试clean,谢谢，如有问题可能还需要请教您

我之前用iPhone6砸壳，在iPhone7P上运行，要在plist文件里面加设备型号，然后重新压缩成ipa是可以用的。你注意看一下你的ipa文件结构是不是.ipa->Payload->.app。Payload的文件名一定要这样，不能小写，也不能多字。

**Comment by AmandaIsLHY** [comment]
<img width="874" alt="屏幕快照 2019-12-03 下午4 48 31" src="https://user-images.githubusercontent.com/50317941/70036300-73a85480-15ef-11ea-87e8-38df8ec438fa.png">
我已根据常见问题1 ，查看了IPA 中二进制文件的架构 armv7 armv64 并在工程的valid architectures 进行了相应的设置，可仍报图中错误

**Comment by paradiseduo** [comment]
> <img alt="屏幕快照 2019-12-03 下午4 48 31" width="874" src="https://user-images.githubusercontent.com/50317941/70036300-73a85480-15ef-11ea-87e8-38df8ec438fa.png">
> 
> 我已根据常见问题1 ，查看了IPA 中二进制文件的架构 armv7 armv64 并在工程的valid architectures 进行了相应的设置，可仍报图中错误

那就把这个库先删掉吧，其实工程中没有用到这个
