### ISSUE TITLE
求助，在非越狱下安装会崩溃

### ISSUE THREAD

**Issue by CDKK** [paradiseduo/IPAPatch#2]
如下提示：
[*] ================================
[*] Dobby
[*] ================================
[*] dobby in debug log mode, disable with cmake flag "-DDOBBY_DEBUG=OFF"
warning: failed to set breakpoint site at 0x1002aa22c for breakpoint -5.1: error: 9 sending the breakpoint request

可否重新cmake一个DDOBBY_DEBUG=OFF 的工程呢，我想试试在非越狱下是否可行，感谢。

**Comment by CDKK** [comment]
cmake .. -G Xcode \
-DCMAKE_TOOLCHAIN_FILE=cmake/ios.toolchain.cmake \
-DPLATFORM=OS64 -DARCHS="arm64" -DCMAKE_SYSTEM_PROCESSOR=arm64 \
-DENABLE_BITCODE=0 -DENABLE_ARC=0 -DENABLE_VISIBILITY=1 -DDEPLOYMENT_TARGET=9.3 \
-DDOBBY_GENERATE_SHARED=OFF -DDOBBY_DEBUG=OFF

**Comment by paradiseduo** [comment]
如果不需要使用Dobby，可以直接将Assets--Frameworks路径下的Dobby.framework移除就好
![image](https://user-images.githubusercontent.com/14846965/110405451-990df300-80bb-11eb-9672-826856fc6cdc.png)

另外IPAPatch重签名的APP是可以在非越狱机上直接运行的。
