### ISSUE TITLE
关于【本工程集成了常见的反调试方法的绕过，如ptrace，syscall，sysctl，isatty等】的疑问

### ISSUE THREAD

**Issue by hehuajun** [paradiseduo/IPAPatch#3]
我用你的这个工程试了下某红书，并不能绕过其反调试保护。目前我用的是croc,debugme，两个命令在lldb模式下绕过的。请问你这个项目里面能够实现croc，debugme的功能吗？或者将这两个添加进来？

**Comment by paradiseduo** [comment]
小红书的反调试做的比较高端，用xia0LLDB挺好的

**Comment by paradiseduo** [comment]
你试试现在能不能绕过小红书的反调试
