### ISSUE TITLE
The file “IPAPatch-DummyApp.app” couldn’t be opened because you don’t have permission to v…

### ISSUE THREAD

**Issue by lgq2015** [paradiseduo/IPAPatch#4]

**Comment by paradiseduo** [comment]
你把要重签名的app包重命名为app.ipa并放到Assets目录下了吗？

**Comment by lgq2015** [comment]
使用方法：将砸壳后的ipa包重命名为app.ipa，然后放入Assets文件夹下，打开IPAPatch工程直接运行即可，运行前请选好证书，改好bundleID
Open IPAPatch.xcodeproj
In the Project Editor, Select Target IPAPatch-DummyApp
Display Name defaults to "💊", this is used as prefix of the final display name.
Change Bundle Identifier to match your provisioning profiles
Fix signing issues if any.

**Comment by lgq2015** [comment]
com.ysd.resign.kings

**Comment by lgq2015** [comment]
我重新clone了一份代码 可以跑起来了 可能操作有误导致的。

**Comment by lgq2015** [comment]
RESTORE_SYMBOLS 这个配置引起的 @paradiseduo 这个配置为1 就会出现don’t have permission t。 vx  jrac2ca

**Comment by lgq2015** [comment]
MACH_O_FILE_NAME=`basename $TEMP_APP_PATH .app` 去掉 .app之前的空格

**Comment by paradiseduo** [comment]
提个PR吧
