### ISSUE TITLE
在xcode Version 12.5.1 (12E507) 中运行Success,但是手机没有任何反应

### ISSUE THREAD

**Issue by awake1t** [paradiseduo/IPAPatch#8]
环境:  MacOs Big Sur
Ver: 11.2.3
M1 芯片

在xcode Version 12.5.1 (12E507) 中运行Success,但是手机没有任何反应。 初步调试下，script 中的 Tools/path.sh 都没有被执行。 但是 同样的环境，运行这个版本( https://github.com/Naituw/IPAPatch/releases/tag/1.0)，就可以运行。

朋友用Xcode11，就可以正常运行本项目。

**Comment by paradiseduo** [comment]
你的target选对了吗

**Comment by awake1t** [comment]
感谢回复哈，target 如截图，显示 Build Success，但是手机没有任何反应。  但是运行这个版本( https://github.com/Naituw/IPAPatch/releases/tag/1.0)，就可以运行。

![image](https://user-images.githubusercontent.com/69112564/130003322-315e950c-9db0-447b-83b0-4f3845ce29b4.png)
![image](https://user-images.githubusercontent.com/69112564/130003411-fd2e960f-739b-489d-8bc7-e7b38eafaafb.png)

![image](https://user-images.githubusercontent.com/69112564/130003181-e8662c38-03be-4170-9235-69c5f181a414.png)

**Comment by awake1t** [comment]
大佬 如果方便也可以加微信交流，我的微信 drunk_kk

**Comment by paradiseduo** [comment]
选APP的target
![image](https://user-images.githubusercontent.com/14846965/130005108-606eb666-278f-473b-89c9-5a1abd2ff4f6.png)

**Comment by awake1t** [comment]
谢谢大佬 已解决
